server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t5hHVxxaCvfToBwqWAe
      secret-key: HFz31WqoWVlatJgzuUpK24XGeAZcVi
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: online-shop-hq
  application:
    name: onlineshop-third-party
