server:
  port: 13000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.10.100
    port: 6379
  session:
    store-type: redis
  application:
    name: onlineshop-search

  thymeleaf:
    cache: false