spring:
  cloud:
    gateway:
      routes:
        - id: goods_route
          uri: lb://onlineshop-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: three_party_route
          uri: lb://onlineshop-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}

        - id: userRoute
          uri: lb://onlineshop-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: wareHouseRoute
          uri: lb://onlineshop-warehouse
          predicates:
            - Path=/api/warehouse/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

        - id: onlineshop_host_route
          uri: lb://onlineshop-goods
          predicates:
            - Host=**.onlineshop.hlju.com,onlineshop.hlju.com