server:
  port: 14000
  servlet:
    session:
      timeout: 30m
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: onlineshop-auth
  redis:
    host: 192.168.10.100
    port: 6379

  thymeleaf:
    cache: false
  session:
    store-type: redis

