server:
  port: 9000
spring:
  datasource:
    username: hq
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/onlineshop_gms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
  redis:
    host: 192.168.10.100
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000
#      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.hlju.onlineshop.goods: debug

onlineshop:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10
