server:
  port: 16000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.10.100
    port: 6379
  application:
    name: onlineshop-cart
onlineshop:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10